[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "website-embed"
version = "0.1.0"
description = "Website embedding service using Modal, Playwright, and CLIP"
authors = [{name = "Your Name"}]
license = {text = "MIT"}
requires-python = ">=3.11"
dependencies = [
    "numpy==1.24.4",
    "fastapi[standard]==0.115.6",
    "playwright==1.41.0",
    "open-clip-torch==2.24.0",
    "torch==2.1.2",
    "torchvision==0.16.2",
    "timm>=0.9.16",
    "Pillow==10.2.0",
    "requests==2.31.0",
    "modal",
    "transformers>=4.21.0",
    "beautifulsoup4>=4.11.0",
    "dreamsim",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
]

[tool.setuptools]
package-dir = {"" = "."}
packages = ["embed"] 